### ISSUE TITLE
Use the official requestSuiFromFaucetV0() to fund an address

### ISSUE THREAD

**Issue by kkomelin** [juzybits/polymedia-suitcase#2]
I suggest using the [official API](https://sdk.mystenlabs.com/typescript/faucet) from `@mysten/sui.js/faucet` to fund an address in `requestSuiFromFaucet()` instead of making a lower-level HTTP call through `fetch()`.

**Comment by juzybits** [comment]
Done with https://github.com/juzybits/polymedia-suitcase/commit/1f54ffddf580b01bf83354b10293d322eb576b33. Thanks for the suggestion!

**Comment by kkomelin** [comment]
Great. Thanks @juzybits!
